// Package event defines the canonical event model shared by every pipeline
// stage, plus its single wire serialization: flat JSON with dotted keys
// (gen_ai.* per OTel GenAI semantic conventions, hc_agent.* per the HOTS
// healthcare extension).
package event

import (
	"encoding/json"
	"time"
)

// CanonicalEvent is the normalized form of one agent log event. Parsers
// produce it, redact/enrich stages mutate it, and every output renders it
// through MarshalFlat — one serialization for all destinations.
type CanonicalEvent struct {
	// Identity & time
	EventID   string    // ULID, generated by the pipeline if the source lacks one
	Timestamp time.Time // from the source log line
	TraceID   string    // propagated if present in source, else empty
	SpanID    string

	// OTel GenAI alignment (gen_ai.*)
	Operation    string // "chat" | "execute_tool" | "invoke_agent" | "create_agent"
	Model        string // gen_ai.request.model
	Provider     string // gen_ai.provider.name
	InputTokens  *int64 // gen_ai.usage.input_tokens (nil if unknown)
	OutputTokens *int64
	ToolName     string // gen_ai.tool.name

	// Healthcare extension (hc_agent.*)
	PolicyDecision string   // "allow" | "deny" | "sanitize" | "halt" | "n/a"
	PolicyLayer    string   // "rbac" | "contraindication" | "injection" | "circuit_breaker" | "qfire_scope" | "qfire_phi" | ""
	RequirementIDs []string // filled by the enrich stage
	AutonomyLevel  string
	OversightMode  string // "autonomous" | "hitl" | "on_behalf"
	PatientCtxHash string // HMAC-SHA256(salt, patient_ref) — never the raw ref
	PHIRedactions  int    // count of scrubbed values in this event

	// Relay provenance (hc_agent.relay.*)
	RelayVersion   string
	SchemaVersion  string
	MappingVersion string
	ConfigHash     string
	SourceFormat   string // "haarf_audit" | "qfire" | "llm_sdk"

	// Raw holds allowlisted residual fields, already keyed with their final
	// dotted names. Reserved keys (owned by the struct fields above) are
	// ignored at serialization time so a source line can never spoof them.
	Raw map[string]any
}

// reserved is the set of dotted keys owned by CanonicalEvent struct fields.
var reserved = map[string]struct{}{
	"event.id":                       {},
	"event.timestamp":                {},
	"trace_id":                       {},
	"span_id":                        {},
	"gen_ai.operation.name":          {},
	"gen_ai.request.model":           {},
	"gen_ai.provider.name":           {},
	"gen_ai.usage.input_tokens":      {},
	"gen_ai.usage.output_tokens":     {},
	"gen_ai.tool.name":               {},
	"hc_agent.policy.decision":       {},
	"hc_agent.policy.layer":          {},
	"hc_agent.haarf.requirement_ids": {},
	"hc_agent.autonomy.level":        {},
	"hc_agent.oversight.mode":        {},
	"hc_agent.patient.context_hash":  {},
	"hc_agent.phi.redaction_count":   {},
	"hc_agent.relay.version":         {},
	"hc_agent.relay.schema_version":  {},
	"hc_agent.relay.mapping_version": {},
	"hc_agent.relay.config_hash":     {},
	"hc_agent.relay.source_format":   {},
}

// MarshalFlat renders the event as one line of flat JSON with dotted keys.
// encoding/json sorts map keys, so output is deterministic byte-for-byte
// given identical field values — the property the golden tests rely on.
func (e *CanonicalEvent) MarshalFlat() ([]byte, error) {
	m := make(map[string]any, len(e.Raw)+22)
	for k, v := range e.Raw {
		if _, ok := reserved[k]; !ok {
			m[k] = v
		}
	}

	m["event.id"] = e.EventID
	m["event.timestamp"] = e.Timestamp.UTC().Format(time.RFC3339Nano)
	putNonEmpty(m, "trace_id", e.TraceID)
	putNonEmpty(m, "span_id", e.SpanID)

	putNonEmpty(m, "gen_ai.operation.name", e.Operation)
	putNonEmpty(m, "gen_ai.request.model", e.Model)
	putNonEmpty(m, "gen_ai.provider.name", e.Provider)
	if e.InputTokens != nil {
		m["gen_ai.usage.input_tokens"] = *e.InputTokens
	}
	if e.OutputTokens != nil {
		m["gen_ai.usage.output_tokens"] = *e.OutputTokens
	}
	putNonEmpty(m, "gen_ai.tool.name", e.ToolName)

	putNonEmpty(m, "hc_agent.policy.decision", e.PolicyDecision)
	putNonEmpty(m, "hc_agent.policy.layer", e.PolicyLayer)
	if len(e.RequirementIDs) > 0 {
		m["hc_agent.haarf.requirement_ids"] = e.RequirementIDs
	}
	putNonEmpty(m, "hc_agent.autonomy.level", e.AutonomyLevel)
	putNonEmpty(m, "hc_agent.oversight.mode", e.OversightMode)
	putNonEmpty(m, "hc_agent.patient.context_hash", e.PatientCtxHash)
	m["hc_agent.phi.redaction_count"] = e.PHIRedactions

	putNonEmpty(m, "hc_agent.relay.version", e.RelayVersion)
	putNonEmpty(m, "hc_agent.relay.schema_version", e.SchemaVersion)
	putNonEmpty(m, "hc_agent.relay.mapping_version", e.MappingVersion)
	putNonEmpty(m, "hc_agent.relay.config_hash", e.ConfigHash)
	putNonEmpty(m, "hc_agent.relay.source_format", e.SourceFormat)

	return json.Marshal(m)
}

func putNonEmpty(m map[string]any, key, val string) {
	if val != "" {
		m[key] = val
	}
}
